import type { CSSProperties } from 'react';

/** 專案甘特圖 / 簡報模式樣式（沿用 workflow-designer styles.ts 內聯樣式風格）。 */
export const ui: Record<string, CSSProperties> = {
  layout: { display: 'flex', gap: '1rem', alignItems: 'flex-start' },
  sidebar: { flex: '0 0 220px', borderRight: '1px solid #e2e8f0', paddingRight: '1rem' },
  main: { flex: 1, minWidth: 0 },
  toolbar: { display: 'flex', gap: '0.6rem', alignItems: 'center', marginBottom: '0.75rem', flexWrap: 'wrap' },
  spacer: { flex: 1 },
  btn: {
    padding: '0.4rem 0.8rem',
    border: '1px solid #cbd5e1',
    borderRadius: 6,
    background: '#f8fafc',
    cursor: 'pointer',
    fontSize: '0.9rem',
  },
  btnPrimary: { borderColor: '#2563eb', background: '#2563eb', color: '#fff' },
  kpiRow: { display: 'flex', gap: '0.6rem', flexWrap: 'wrap', marginBottom: '0.9rem' },
  kpiCard: {
    flex: '1 1 120px',
    minWidth: 110,
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: '0.6rem 0.75rem',
    background: '#fff',
  },
  kpiLabel: { fontSize: '0.78rem', color: '#64748b', marginBottom: 2 },
  kpiValue: { fontSize: '1.4rem', fontWeight: 700, lineHeight: 1.1 },
  headline: { fontSize: '0.95rem', color: '#334155', marginBottom: '0.75rem' },
  chart: {
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    background: '#fff',
    padding: '0.5rem 0.75rem',
    position: 'relative',
    overflow: 'hidden',
  },
  monthsBar: { position: 'relative', height: 22, borderBottom: '1px solid #e2e8f0', marginBottom: 6 },
  monthTick: { position: 'absolute', top: 0, fontSize: '0.72rem', color: '#94a3b8', transform: 'translateX(2px)' },
  rowLine: { position: 'relative', display: 'flex', alignItems: 'center' },
  rowLabel: { flex: '0 0 160px', fontSize: '0.85rem', color: '#334155', paddingRight: 8, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  rowTrack: { position: 'relative', flex: 1, height: '100%' },
  bar: { position: 'absolute', borderRadius: 5, top: '50%', transform: 'translateY(-50%)', overflow: 'hidden' },
  barFill: { position: 'absolute', left: 0, top: 0, bottom: 0, opacity: 0.55 },
  todayLine: { position: 'absolute', top: 0, bottom: 0, width: 2, background: '#ef4444', zIndex: 3 },
  exclusionBand: { position: 'absolute', top: 0, bottom: 0, background: 'repeating-linear-gradient(45deg,#e2e8f0,#e2e8f0 4px,transparent 4px,transparent 8px)', zIndex: 1 },
  pill: {
    display: 'inline-block',
    padding: '0.05rem 0.45rem',
    borderRadius: 999,
    fontSize: '0.72rem',
    marginLeft: 6,
  },
  muted: { color: '#64748b', fontSize: '0.82rem' },
  listItem: {
    display: 'block',
    width: '100%',
    textAlign: 'left',
    padding: '0.45rem 0.55rem',
    marginBottom: '0.35rem',
    border: '1px solid #e2e8f0',
    borderRadius: 6,
    background: '#fff',
    fontSize: '0.85rem',
  },
  /** 簡報模式覆蓋層（沉浸全螢幕）。 */
  presentationOverlay: {
    position: 'fixed',
    inset: 0,
    background: '#ffffff',
    zIndex: 1000,
    padding: '1.5rem 2rem',
    overflow: 'auto',
    boxSizing: 'border-box',
  },
};
