import type { CSSProperties } from 'react';

export const ui: Record<string, CSSProperties> = {
  layout: { display: 'flex', gap: '1rem', alignItems: 'flex-start' },
  sidebar: { flex: '0 0 240px', borderRight: '1px solid #e2e8f0', paddingRight: '1rem' },
  editor: { flex: 1, minWidth: 0 },
  listItem: {
    display: 'block',
    width: '100%',
    textAlign: 'left',
    padding: '0.5rem 0.6rem',
    marginBottom: '0.35rem',
    border: '1px solid #e2e8f0',
    borderRadius: 6,
    background: '#fff',
    cursor: 'pointer',
  },
  listItemActive: { borderColor: '#2563eb', background: '#eff6ff' },
  card: {
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    padding: '0.75rem 0.9rem',
    marginBottom: '0.75rem',
    background: '#fff',
  },
  label: { display: 'block', fontSize: '0.8rem', color: '#475569', marginBottom: 2 },
  input: {
    width: '100%',
    padding: '0.35rem 0.5rem',
    border: '1px solid #cbd5e1',
    borderRadius: 5,
    fontSize: '0.9rem',
    boxSizing: 'border-box',
  },
  row: { display: 'flex', gap: '0.6rem', flexWrap: 'wrap', marginBottom: '0.5rem' },
  btn: {
    padding: '0.35rem 0.7rem',
    border: '1px solid #cbd5e1',
    borderRadius: 5,
    background: '#f8fafc',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  btnPrimary: { borderColor: '#2563eb', background: '#2563eb', color: '#fff' },
  btnDanger: { borderColor: '#dc2626', color: '#dc2626', background: '#fff' },
  pill: {
    display: 'inline-block',
    padding: '0.1rem 0.45rem',
    borderRadius: 999,
    fontSize: '0.72rem',
    background: '#f1f5f9',
    color: '#334155',
    marginLeft: 4,
  },
  nextLine: { fontSize: '0.82rem', color: '#2563eb', marginTop: 4 },
  warn: { color: '#b45309', fontSize: '0.82rem' },
  err: { color: '#dc2626', fontSize: '0.82rem' },
  muted: { color: '#64748b', fontSize: '0.82rem' },
};
